name: arthiksathi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.1.0
  fluttertoast: ^8.2.2  # For showing toast messages
  provider: ^6.0.5     # For state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - lib/Assets/Group84.png

flutter_native_splash:
  color: "#0063dd"
  android: true
  ios: true